language: java
jdk: openjdk8

before_install:
  - shopt -s expand_aliases
  - alias mvn='mvn -DskipTests --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

deploy:
  provider: script
  script: mvn -s .travis.settings.xml -DskipTests deploy
  skip_cleanup: true
  on:
    branch: master

before_cache:
  - rm -rf ~/.m2/repository/org/opencast/*annotation*
  - sudo chown -R travis:travis ~/.m2

cache:
  directories:
    - $HOME/.m2
    - frontend/node
    - frontend/node_modules
